fastapi:
  debug: false
databases:
  default:
    ENGINE: "mongodb"
    DRIVER: "motor"
    NAME: "app_db"
    USER: "app_user"
    PASSWORD: "4dm1n4dm1n"
    HOST: "mongo"
    PORT: "27017"
usps:
  userID: "823EMERG7469"
