version: "0.1"
volumes:
  mongo_data:
services:
  backend:
    build: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo:5.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "app_user"
      MONGO_INITDB_ROOT_PASSWORD: "4dm1n4dm1n"
    volumes:
      - mongo_data:/data/app_db
    ports:
      - 27017:27017
  frontend:
    build: ./frontend
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    ports:
      - 8080:8080
